[project]
name = "GoldyBot"
description = "Yet another another rewrite of Goldy Bot, a discord bot framework for my own bots."
authors = [
    {name = "Goldy", email = "goldy@devgoldy.me"},
]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = [
    "goldybot", "goldy bot", "Goldy Bot", "Goldy Bot V4", "Goldy Bot V3", "goldy", "Goldy Bot V5"
]
classifiers = [
	'Operating System :: Microsoft :: Windows :: Windows 11',
    'Operating System :: Microsoft :: Windows :: Windows 10',
    'Operating System :: POSIX :: Linux',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11'
]
dependencies = [
    "requests",
    "importlib-metadata; python_version<'3.8'",

    "devgoldyutils>=2.0.1",
    "nextcore@git+https://github.com/nextsnake/nextcore",
    "click",
    "python-decouple"
]

dynamic = ["version"]

[project.urls]
GitHub = "https://github.com/Goldy-Bot/Goldy-Bot-V5"
BugTracker = "https://github.com/Goldy-Bot/Goldy-Bot-V5/issues"
ChangeLog = "https://github.com/Goldy-Bot/Goldy-Bot-V5/master/CHANGELOG.md"

[tool.setuptools.dynamic]
version = { attr = "GoldyBot.info.VERSION" }

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.scripts]
goldybot = "GoldyBot.cli.__main__:goldy_bot"