lint.ignore = ["E501", "E402", "E702", "E701", "E731"]

target-version = "py38"

[lint.per-file-ignores]
"__init__.py" = ["F403"]
"scripts/*" = ["F401"]
"GoldyBot/*" = ["F401"]
"GoldyBot/cli/__main__.py" = ["E741"]
"GoldyBot/logging.py" = ["F401"]
"GoldyBot/utils/_lambda.py" = ["E731"]
"tests/__init__.py" = ["F401"]