version = 2

[branding]
name = "Goldy Bot"
emoticon = "🥞"

[extensions]
repos = []
include = [] # Find extension code names at https://github.com/Goldy-Bot/goldybot.repo
ignore = [] # e.g. ignore = ["music.sharing"] <-- {extension}.{module/command}

[extensions.load]
directory = "./extensions"
raise_on_error = true

# It's extremely recommended you include a test guild id 
# if you are testing/developing, otherwise global commands will be 
# loaded instead of guild commands resulting in commands taking FOREVER to load.

# [development]
# test_guild_id = ""
# developer_id = ""