__all__ = (
    "GOLDY_INTENTS",
)

GUILDS_INTENT = 1 << 0
GUILD_MEMBERS_INTENT = 1 << 1
GUILD_MODERATION_INTENT = 1 << 2
GUILD_EMOJIS_AND_STICKERS_INTENT = 1 << 3
GUILD_INTEGRATIONS_INTENT = 1 << 4
GUILD_WEBHOOKS_INTENT = 1 << 5
GUILD_INVITES_INTENT = 1 << 6
GUILD_VOICE_STATES_INTENT = 1 << 7
GUILD_PRESENCES_INTENT = 1 << 8
GUILD_MESSAGES_INTENT = 1 << 9
GUILD_MESSAGE_REACTIONS_INTENT = 1 << 10
GUILD_MESSAGE_TYPING_INTENT = 1 << 11
DIRECT_MESSAGES_INTENT = 1 << 12
DIRECT_MESSAGE_REACTIONS_INTENT = 1 << 13
DIRECT_MESSAGE_TYPING_INTENT = 1 << 14
MESSAGE_CONTENT_INTENT = 1 << 15
GUILD_SCHEDULED_EVENTS_INTENT = 1 << 16
AUTO_MODERATION_CONFIGURATION_INTENT = 1 << 20
AUTO_MODERATION_EXECUTION_INTENT = 1 << 21

GOLDY_INTENTS = (
    GUILD_MESSAGES_INTENT | 
    MESSAGE_CONTENT_INTENT | 
    GUILDS_INTENT
)
"""Discord intents used by the framework."""